# To enable logging, use the snippet per the documentation.
# Delaying log output may help catch issues close to startup. Uncomment and adjust if necessary (default is 1000ms)
# #CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=3000

